/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz of platform commands send
    info_freq: 10.0  # Hz of platform info publish
    max_thrust: 15.0  # N
    min_thrust: 0.15  # N
    external_odom: false  # Use external odometry source